// Importing modules

const nodemailer = require('nodemailer');
const { google } = require('googleapis');

// Creating variables
// Pass the clinetID, clientSecret and refreshToken generated by user from Google API Console into the respective variables.
// If you don't have above credentials visit https://console.cloud.google.com/ to generate your own.

const CLIENT_ID = 'YOUR CLIENT ID';     // Pass client ID here
const CLEINT_SECRET = 'YOUR CLIENT SECRET';  // Pass client secret here
const REDIRECT_URI = 'https://developers.google.com/oauthplayground';
const REFRESH_TOKEN = 'YOUR REFRESH TOKEN';  // Pass refresh token here


const oAuth2Client = new google.auth.OAuth2(
  CLIENT_ID,
  CLEINT_SECRET,
  REDIRECT_URI
);

oAuth2Client.setCredentials({ refresh_token: REFRESH_TOKEN });

async function sendMail() {
  try {
    const accessToken = await oAuth2Client.getAccessToken();

    const transport = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        type: 'OAuth2',
        user: 'yours authorised email address',
        clientId: CLIENT_ID,
        clientSecret: CLEINT_SECRET,
        refreshToken: REFRESH_TOKEN,
        accessToken: accessToken,
      },
    });

    // Edit the options below as per the email to be send

    const mailOptions = {
      from: 'SENDER NAME <yours authorised email address@gmail.com>',   // Replace SENDER NAME by the name you want the reciver to revice the mail.Fill your email in the angular brackets.
      to: 'to email address here',   // The recivers email address goes here.
      subject: 'Mail from gmail using API',  // Fill the subject of the mail.
      text: 'Mail from gmail using API',  // Here goes the text content of the mail.
      html: '<h1>Mail from gmail using API</h1>',  // Here goes HTML content of the mail (Optional)
    };

    const result = await transport.sendMail(mailOptions);
    return result;
  } catch (error) {
    return error;
  }
}

sendMail()
  .then((result) => console.log('Email sent......', result))
  .catch((error) => console.log(error.message));

// Open your console and navigate to the location where this file is stored.
// run 'npm install nodemailer' to install nodemailer module.
// run 'node index.js' to run this file.
// It will take few seconds to send the mail and result will to shown in console.
